name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 0 * * *'

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list:https://medium.com/feed/@amefonaffia
          comment_tag_name:"Medium"
          commit_message:"Updated readme with the latest medium post"
